set_property IOSTANDARD LVCMOS33 [get_ports adcClk]
# set_property IOSTANDARD LVCMOS33 [get_ports dacWrt]
set_property IOSTANDARD LVCMOS33 [get_ports {adcData[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adcData[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adcData[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adcData[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adcData[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adcData[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adcData[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adcData[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adcData[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adcData[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adcData[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adcData[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adcData[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adcData[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adcData[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adcData[15]}]
set_property PACKAGE_PIN G14 [get_ports adcClk]
# set_property PACKAGE_PIN B11 [get_ports dacWrt]
set_property PACKAGE_PIN G12 [get_ports {adcData[0]}]
set_property PACKAGE_PIN F12 [get_ports {adcData[1]}]
set_property PACKAGE_PIN G11 [get_ports {adcData[2]}]
set_property PACKAGE_PIN F10 [get_ports {adcData[3]}]
set_property PACKAGE_PIN F8  [get_ports {adcData[4]}]
set_property PACKAGE_PIN A8  [get_ports {adcData[5]}]
set_property PACKAGE_PIN F9  [get_ports {adcData[6]}]
set_property PACKAGE_PIN B9  [get_ports {adcData[7]}]
set_property PACKAGE_PIN D8  [get_ports {adcData[8]}]
set_property PACKAGE_PIN A9  [get_ports {adcData[9]}]
set_property PACKAGE_PIN E13 [get_ports {adcData[10]}]
set_property PACKAGE_PIN C9  [get_ports {adcData[11]}]
set_property PACKAGE_PIN E10 [get_ports {adcData[12]}]
set_property PACKAGE_PIN B11 [get_ports {adcData[13]}]
set_property PACKAGE_PIN E11 [get_ports {adcData[14]}]
set_property PACKAGE_PIN C11 [get_ports {adcData[15]}]


