set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property PACKAGE_PIN G22 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS18 [get_ports rgmii_rxc]
set_property IOSTANDARD LVCMOS18 [get_ports rgmii_txc]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rxd[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rxd[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rxd[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rxd[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_txd[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_txd[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_txd[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_txd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]
set_property PACKAGE_PIN D26 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS18 [get_ports rgmii_rx_ctl]
set_property IOSTANDARD LVCMOS18 [get_ports rgmii_rst_n]
set_property IOSTANDARD LVCMOS18 [get_ports rgmii_tx_ctl]
set_property PACKAGE_PIN Y2 [get_ports rgmii_rst_n]
set_property PACKAGE_PIN AF4 [get_ports rgmii_rx_ctl]
set_property PACKAGE_PIN Y1 [get_ports rgmii_tx_ctl]
set_property PACKAGE_PIN AC2 [get_ports rgmii_txc]
set_property PACKAGE_PIN AC1 [get_ports {rgmii_txd[0]}]
set_property PACKAGE_PIN AB1 [get_ports {rgmii_txd[1]}]
set_property PACKAGE_PIN AB4 [get_ports {rgmii_txd[2]}]
set_property PACKAGE_PIN Y3 [get_ports {rgmii_txd[3]}]
set_property PACKAGE_PIN AB2 [get_ports rgmii_rxc]
set_property PACKAGE_PIN AF3 [get_ports {rgmii_rxd[0]}]
set_property PACKAGE_PIN AC3 [get_ports {rgmii_rxd[1]}]
set_property PACKAGE_PIN AE2 [get_ports {rgmii_rxd[2]}]
set_property PACKAGE_PIN AE1 [get_ports {rgmii_rxd[3]}]

##################################################################################################

##

##  Xilinx, Inc. 2010            www.xilinx.com

##  Wed Sep  4 15:34:04 2024


##  Generated by MIG Version 4.2

##

##################################################################################################

##  File name :       dfi_ddr3.xdc

##  Details :     Constraints file

##                    FPGA Family:       KINTEX7

##                    FPGA Part:         XC7K325T-FFG676

##                    Speedgrade:        -2

##                    Design Entry:      VERILOG

##                    Frequency:         100 MHz

##                    Time Period:       5000 ps

##################################################################################################



##################################################################################################

## Controller 0

## Memory Device: DDR3_SDRAM->Components->MT41K256M16XX-107

## Data Width: 16

## Time Period: 1250

## Data Mask: 1

##################################################################################################

#set_property IOSTANDARD LVCMOS33 [get_ports clk]
#set_property PACKAGE_PIN G22 [get_ports clk]
#set_property IOSTANDARD LVCMOS33 [get_ports rstN]
#set_property PACKAGE_PIN D26 [get_ports rstN]
#set_property IOSTANDARD LVCMOS33 [get_ports key]
#set_property PACKAGE_PIN J26 [get_ports key]

set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_ckN[*]}]

set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_ckP[*]}]

#create_clock -period 1.25 [get_ports sys_clk_i]
#create_clock -period 5 [get_ports clk_ref_i]


############## NET - IOSTANDARD ##################




# PadFunction: IO_L2P_T0_32

set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[0]}]

set_property SLEW FAST [get_ports {ddr3_dq[0]}]

set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[0]}]

set_property PACKAGE_PIN AF14 [get_ports {ddr3_dq[0]}]



# PadFunction: IO_L1N_T0_32

set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[1]}]

set_property SLEW FAST [get_ports {ddr3_dq[1]}]

set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[1]}]

set_property PACKAGE_PIN AF17 [get_ports {ddr3_dq[1]}]



# PadFunction: IO_L4N_T0_32

set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[2]}]

set_property SLEW FAST [get_ports {ddr3_dq[2]}]

set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[2]}]

set_property PACKAGE_PIN AE15 [get_ports {ddr3_dq[2]}]



# PadFunction: IO_L1P_T0_32

set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[3]}]

set_property SLEW FAST [get_ports {ddr3_dq[3]}]

set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[3]}]

set_property PACKAGE_PIN AE17 [get_ports {ddr3_dq[3]}]



# PadFunction: IO_L6P_T0_32

set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[4]}]

set_property SLEW FAST [get_ports {ddr3_dq[4]}]

set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[4]}]

set_property PACKAGE_PIN AD16 [get_ports {ddr3_dq[4]}]



# PadFunction: IO_L5N_T0_32

set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[5]}]

set_property SLEW FAST [get_ports {ddr3_dq[5]}]

set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[5]}]

set_property PACKAGE_PIN AF20 [get_ports {ddr3_dq[5]}]



# PadFunction: IO_L4P_T0_32

set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[6]}]

set_property SLEW FAST [get_ports {ddr3_dq[6]}]

set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[6]}]

set_property PACKAGE_PIN AD15 [get_ports {ddr3_dq[6]}]



# PadFunction: IO_L5P_T0_32

set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[7]}]

set_property SLEW FAST [get_ports {ddr3_dq[7]}]

set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[7]}]

set_property PACKAGE_PIN AF19 [get_ports {ddr3_dq[7]}]



# PadFunction: IO_L10N_T1_32

set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[8]}]

set_property SLEW FAST [get_ports {ddr3_dq[8]}]

set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[8]}]

set_property PACKAGE_PIN AB15 [get_ports {ddr3_dq[8]}]



# PadFunction: IO_L8P_T1_32

set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[9]}]

set_property SLEW FAST [get_ports {ddr3_dq[9]}]

set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[9]}]

set_property PACKAGE_PIN AC14 [get_ports {ddr3_dq[9]}]



# PadFunction: IO_L11N_T1_SRCC_32

set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[10]}]

set_property SLEW FAST [get_ports {ddr3_dq[10]}]

set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[10]}]

set_property PACKAGE_PIN AA18 [get_ports {ddr3_dq[10]}]



# PadFunction: IO_L7P_T1_32

set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[11]}]

set_property SLEW FAST [get_ports {ddr3_dq[11]}]

set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[11]}]

set_property PACKAGE_PIN AA14 [get_ports {ddr3_dq[11]}]



# PadFunction: IO_L12P_T1_MRCC_32

set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[12]}]

set_property SLEW FAST [get_ports {ddr3_dq[12]}]

set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[12]}]

set_property PACKAGE_PIN AB16 [get_ports {ddr3_dq[12]}]



# PadFunction: IO_L10P_T1_32

set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[13]}]

set_property SLEW FAST [get_ports {ddr3_dq[13]}]

set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[13]}]

set_property PACKAGE_PIN AB14 [get_ports {ddr3_dq[13]}]



# PadFunction: IO_L11P_T1_SRCC_32

set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[14]}]

set_property SLEW FAST [get_ports {ddr3_dq[14]}]

set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[14]}]

set_property PACKAGE_PIN AA17 [get_ports {ddr3_dq[14]}]



# PadFunction: IO_L8N_T1_32

set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[15]}]

set_property SLEW FAST [get_ports {ddr3_dq[15]}]

set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[15]}]

set_property PACKAGE_PIN AD14 [get_ports {ddr3_dq[15]}]



# PadFunction: IO_L4P_T0_33

set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[14]}]

set_property SLEW FAST [get_ports {ddr3_addr[14]}]

set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[14]}]

set_property PACKAGE_PIN Y8 [get_ports {ddr3_addr[14]}]



# PadFunction: IO_L2N_T0_33

set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[13]}]

set_property SLEW FAST [get_ports {ddr3_addr[13]}]

set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[13]}]

set_property PACKAGE_PIN V7 [get_ports {ddr3_addr[13]}]



# PadFunction: IO_L24N_T3_33

set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[12]}]

set_property SLEW FAST [get_ports {ddr3_addr[12]}]

set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[12]}]

set_property PACKAGE_PIN AF9 [get_ports {ddr3_addr[12]}]



# PadFunction: IO_L14P_T2_SRCC_33

set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[11]}]

set_property SLEW FAST [get_ports {ddr3_addr[11]}]

set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[11]}]

set_property PACKAGE_PIN AA10 [get_ports {ddr3_addr[11]}]



# PadFunction: IO_L12N_T1_MRCC_33

set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[10]}]

set_property SLEW FAST [get_ports {ddr3_addr[10]}]

set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[10]}]

set_property PACKAGE_PIN AD9 [get_ports {ddr3_addr[10]}]



# PadFunction: IO_L13N_T2_MRCC_33

set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[9]}]

set_property SLEW FAST [get_ports {ddr3_addr[9]}]

set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[9]}]

set_property PACKAGE_PIN AC11 [get_ports {ddr3_addr[9]}]



# PadFunction: IO_L8P_T1_33

set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[8]}]

set_property SLEW FAST [get_ports {ddr3_addr[8]}]

set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[8]}]

set_property PACKAGE_PIN AA8 [get_ports {ddr3_addr[8]}]



# PadFunction: IO_L2P_T0_33

set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[7]}]

set_property SLEW FAST [get_ports {ddr3_addr[7]}]

set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[7]}]

set_property PACKAGE_PIN V8 [get_ports {ddr3_addr[7]}]



# PadFunction: IO_L5P_T0_33

set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[6]}]

set_property SLEW FAST [get_ports {ddr3_addr[6]}]

set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[6]}]

set_property PACKAGE_PIN Y11 [get_ports {ddr3_addr[6]}]



# PadFunction: IO_L6N_T0_VREF_33

set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[5]}]

set_property SLEW FAST [get_ports {ddr3_addr[5]}]

set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[5]}]

set_property PACKAGE_PIN W8 [get_ports {ddr3_addr[5]}]



# PadFunction: IO_L12P_T1_MRCC_33

set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[4]}]

set_property SLEW FAST [get_ports {ddr3_addr[4]}]

set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[4]}]

set_property PACKAGE_PIN AC9 [get_ports {ddr3_addr[4]}]



# PadFunction: IO_L4N_T0_33

set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[3]}]

set_property SLEW FAST [get_ports {ddr3_addr[3]}]

set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[3]}]

set_property PACKAGE_PIN Y7 [get_ports {ddr3_addr[3]}]



# PadFunction: IO_L6P_T0_33

set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[2]}]

set_property SLEW FAST [get_ports {ddr3_addr[2]}]

set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[2]}]

set_property PACKAGE_PIN V9 [get_ports {ddr3_addr[2]}]



# PadFunction: IO_L14N_T2_SRCC_33

set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[1]}]

set_property SLEW FAST [get_ports {ddr3_addr[1]}]

set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[1]}]

set_property PACKAGE_PIN AB10 [get_ports {ddr3_addr[1]}]



# PadFunction: IO_L22N_T3_33

set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[0]}]

set_property SLEW FAST [get_ports {ddr3_addr[0]}]

set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[0]}]

set_property PACKAGE_PIN AF8 [get_ports {ddr3_addr[0]}]



# PadFunction: IO_L7N_T1_33

set_property VCCAUX_IO HIGH [get_ports {ddr3_ba[2]}]

set_property SLEW FAST [get_ports {ddr3_ba[2]}]

set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[2]}]

set_property PACKAGE_PIN AF7 [get_ports {ddr3_ba[2]}]



# PadFunction: IO_L13P_T2_MRCC_33

set_property VCCAUX_IO HIGH [get_ports {ddr3_ba[1]}]

set_property SLEW FAST [get_ports {ddr3_ba[1]}]

set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[1]}]

set_property PACKAGE_PIN AB11 [get_ports {ddr3_ba[1]}]



# PadFunction: IO_L8N_T1_33

set_property VCCAUX_IO HIGH [get_ports {ddr3_ba[0]}]

set_property SLEW FAST [get_ports {ddr3_ba[0]}]

set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[0]}]

set_property PACKAGE_PIN AA7 [get_ports {ddr3_ba[0]}]



# PadFunction: IO_L9N_T1_DQS_33

set_property VCCAUX_IO HIGH [get_ports {ddr3_rasN[0]}]

set_property SLEW FAST [get_ports {ddr3_rasN[0]}]

set_property IOSTANDARD SSTL15 [get_ports {ddr3_rasN[0]}]

set_property PACKAGE_PIN AD8 [get_ports {ddr3_rasN[0]}]



# PadFunction: IO_L3P_T0_DQS_33

set_property VCCAUX_IO HIGH [get_ports {ddr3_casN[0]}]

set_property SLEW FAST [get_ports {ddr3_casN[0]}]

set_property IOSTANDARD SSTL15 [get_ports {ddr3_casN[0]}]

set_property PACKAGE_PIN W10 [get_ports {ddr3_casN[0]}]



# PadFunction: IO_L3N_T0_DQS_33

set_property VCCAUX_IO HIGH [get_ports {ddr3_weN[0]}]

set_property SLEW FAST [get_ports {ddr3_weN[0]}]

set_property IOSTANDARD SSTL15 [get_ports {ddr3_weN[0]}]

set_property PACKAGE_PIN W9 [get_ports {ddr3_weN[0]}]



# PadFunction: IO_L5N_T0_33

set_property VCCAUX_IO HIGH [get_ports {ddr3_resetN[0]}]

set_property SLEW FAST [get_ports {ddr3_resetN[0]}]

set_property IOSTANDARD LVCMOS15 [get_ports {ddr3_resetN[0]}]

set_property PACKAGE_PIN Y10 [get_ports {ddr3_resetN[0]}]



# PadFunction: IO_L24P_T3_33

set_property VCCAUX_IO HIGH [get_ports {ddr3_cke[0]}]

set_property SLEW FAST [get_ports {ddr3_cke[0]}]

set_property IOSTANDARD SSTL15 [get_ports {ddr3_cke[0]}]

set_property PACKAGE_PIN AF10 [get_ports {ddr3_cke[0]}]



# PadFunction: IO_L9P_T1_DQS_33

set_property VCCAUX_IO HIGH [get_ports {ddr3_odt[0]}]

set_property SLEW FAST [get_ports {ddr3_odt[0]}]

set_property IOSTANDARD SSTL15 [get_ports {ddr3_odt[0]}]

set_property PACKAGE_PIN AC8 [get_ports {ddr3_odt[0]}]



# PadFunction: IO_L10P_T1_33

set_property VCCAUX_IO HIGH [get_ports {ddr3_csN[0]}]

set_property SLEW FAST [get_ports {ddr3_csN[0]}]

set_property IOSTANDARD SSTL15 [get_ports {ddr3_csN[0]}]

set_property PACKAGE_PIN AB7 [get_ports {ddr3_csN[0]}]



# PadFunction: IO_L2N_T0_32

set_property VCCAUX_IO HIGH [get_ports {ddr3_dm[0]}]

set_property SLEW FAST [get_ports {ddr3_dm[0]}]

set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[0]}]

set_property PACKAGE_PIN AF15 [get_ports {ddr3_dm[0]}]



# PadFunction: IO_L7N_T1_32

set_property VCCAUX_IO HIGH [get_ports {ddr3_dm[1]}]

set_property SLEW FAST [get_ports {ddr3_dm[1]}]

set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[1]}]

set_property PACKAGE_PIN AA15 [get_ports {ddr3_dm[1]}]



# PadFunction: IO_L3P_T0_DQS_32

set_property VCCAUX_IO HIGH [get_ports {ddr3_dqsP[0]}]

set_property SLEW FAST [get_ports {ddr3_dqsP[0]}]

set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqsP[0]}]




# PadFunction: IO_L3N_T0_DQS_32


set_property SLEW FAST [get_ports {ddr3_dqsN[0]}]

set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqsN[0]}]

set_property PACKAGE_PIN AE18 [get_ports {ddr3_dqsP[0]}]
set_property PACKAGE_PIN AF18 [get_ports {ddr3_dqsN[0]}]



# PadFunction: IO_L9P_T1_DQS_32

set_property VCCAUX_IO HIGH [get_ports {ddr3_dqsP[1]}]

set_property SLEW FAST [get_ports {ddr3_dqsP[1]}]

set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqsP[1]}]




# PadFunction: IO_L9N_T1_DQS_32


set_property SLEW FAST [get_ports {ddr3_dqsN[1]}]

set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqsN[1]}]

set_property PACKAGE_PIN Y15 [get_ports {ddr3_dqsP[1]}]
set_property PACKAGE_PIN Y16 [get_ports {ddr3_dqsN[1]}]



# PadFunction: IO_L11P_T1_SRCC_33

set_property VCCAUX_IO HIGH [get_ports {ddr3_ckP[0]}]

set_property SLEW FAST [get_ports {ddr3_ckP[0]}]

set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_ckP[0]}]




# PadFunction: IO_L11N_T1_SRCC_33


set_property SLEW FAST [get_ports {ddr3_ckN[0]}]

set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_ckN[0]}]

set_property PACKAGE_PIN AA9 [get_ports {ddr3_ckP[0]}]
set_property PACKAGE_PIN AB9 [get_ports {ddr3_ckN[0]}]





















## set_property LOC PHASER_IN_PHY_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]

## set_property LOC PHASER_IN_PHY_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]

## set_property LOC PHASER_IN_PHY_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]

## set_property LOC PHASER_IN_PHY_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]




































































#set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/* && IS_SEQUENTIAL}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/device_temp_sync_r1*}] 20



#set_false_path -through [get_pins -hier -filter {NAME =~ */u_iodelay_ctrl/sys_rst}]







